# Generated by Django 5.1.1 on 2024-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('intereses', models.CharField(max_length=200)),
            ],
        ),
    ]
