# Generated by Django 5.1.1 on 2024-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionextra',
            name='biography',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
