# Generated by Django 5.1.1 on 2024-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='creador',
            field=models.CharField(default='A Ingresar', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='productos_imagenes/default_image.jpg', upload_to='productos_imagenes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='stock_arg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
