# Generated by Django 5.1.1 on 2024-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_creador_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='productos_imagenes/default_image.jpg', upload_to='productos_imagenes/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_arg',
            field=models.IntegerField(default=0),
        ),
    ]
